# Generated by Django 5.2 on 2025-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
